### ISSUE TITLE
Does this library exist anymore?

### ISSUE THREAD

**Issue by 2hands10fingers** [chargeover/chargeover_js_example#2]
I can't seem to get it from the provided script sources. What happened?

Doesn't work:
https://assets.chargeover.com/chargeover/minify/?g=chargeover.js
https://dev.chargeover.com/assets/minify/?g=chargeover.js

**Comment by mryanb** [comment]
@2hands10fingers  Yes, the library still exists. Some of the paths have changed though. You will want to make sure its enabled in your account at this page. `/admin/r/feature/view/saas.cojs_enabled`

**Comment by mryanb** [comment]
@2hands10fingers  - Thanks for reporting too! Lets us know if you have any questions about setting up a signup page. Additional docs here: https://developer.chargeover.com/apidocs/js/
